### ISSUE TITLE
Use Logger instead of System.out.println

### ISSUE THREAD

**Issue by anirban-roy** [udger/udger-java#6]
Hi Team,

The library prints the below messages in our applications during startup:

```
Index out of hashmap335 : |gt
Index out of hashmap396 : |twister
Index out of hashmap330 : |crxt
Index out of hashmap463 : |kiano
Index out of hashmap93 : |hudl
Index out of hashmap173 : |one
```

I saw that internally the code relies on System.out.println. Could you please introduce [**Logger**](https://logging.apache.org/log4j/2.x/) and not use println in the entire project. It would be more structured, professional and would allow more control over the desired information on the console/logs. For the above messages we expect them to be logged in DEBUG level.

~Thanks

**Comment by anirban-roy** [comment]
Hey @skybber, Could you guys address this one and release the changes to Maven. The last merge (in memory SQLite DB) is not yet released to Maven. Also since you updated to SQLite latest version, you might want to update the readme.md saying the latest version as well. 

~Thanks

**Comment by skybber** [comment]
There should be some assert, since the logs means problems in table of word in DB. I don't like the idea to add some additional logging library to udger parser.

**Comment by anirban-roy** [comment]
@skybber 

Log does not necessarily mean there is a problem. Refer to the thread [Why choose Log4j over system.out.println](http://stackoverflow.com/questions/2727500/log4j-vs-system-out-println-logger-advantages). A Log could be informative or indicative that a certain step is complete. If you use the logger, you can log at different levels (INFO, WARN, ERROR, DEBUG) and this gives great flexibility. The level would indicate about whether the logs are informative or its an exception or its a warning or its just debug information. All production level code utilizes logger for structured logging. It was allows log processing easy for large scale distributed infrastructure like what we have.

The messages here seems to be debug messages (hard to make sense for end user). If not in favor of using a standard logger, could you please use a class level variable which can be set by developer to enable this logs. Default for this would be false (disabled). 
Refer below for an idea:

```
boolean debug = false; // define a setter as well for programmatic changing. 

void myMethod() {
     if (debug) { // apply before all sysout.println calls
          System.out.println("Index out of hashmap blah blah"); 
     }
```
Hope this helps!

~Thanks

**Comment by skybber** [comment]
fixed in 1.0.6

**Comment by neha-sri** [comment]
Hi, this still doesn't appear to be fixed. 
I do see that `Logger` is being used in `UdgerParser` but there is a `System.out.println` which is still printing `Index out of hashmap` repeatedly on startup. The code is here: https://github.com/udger/udger-java/blob/a5f321a73798de851748cdeb86cce4ed27055306/src/main/java/org/udger/parser/WordDetector.java#L49

Could you please fix this? We are running this code on a cluster and all our tests and runs are littered with this line everywhere even when we are not in debug mode. See example: 

```
Index out of hashmap41 : __weibo__
Index out of hashmap710 : @tab
Index out of hashmap41 : __weibo__
Index out of hashmap710 : @tab
Index out of hashmap41 : __weibo__
Index out of hashmap710 : @tab
Index out of hashmap41 : __weibo__
Index out of hashmap710 : @tab
Index out of hashmap41 : __weibo__
Index out of hashmap710 : @tab
Index out of hashmap41 : __weibo__
Index out of hashmap710 : @tab
```

**Comment by skybber** [comment]
Fixed
